In [1]:
import numpy as np
import json
import pandas as pd
import pickle

with open('../json/main/product1.json', 'r', encoding='utf-8') as f:
    jean1=json.load(f)
with open('../json/main/product2.json', 'r', encoding='utf-8') as f:
    jean2=json.load(f)
        
arr1 = np.zeros(len(jean1)*6)
arr1 = arr1.reshape(6,len(jean1))
arr2 = np.zeros(len(jean2)*6)
arr2 = arr2.reshape(6,len(jean2))

for num in range(0,6):
    for jeans in range(len(jean1)):
        arr1[num][jeans]=jean1[jeans]['ap'][1:-1].split(',')[num]

for num in range(0,6):
    for jeans in range(len(jean2)):
        arr2[num][jeans]=jean2[jeans]['ap'][1:-1].split(',')[num]

arr= np.hstack((arr1,arr2))
temp18,temp23,temp28=arr[0],arr[1],arr[2]
temp=(arr[0],arr[1],arr[2],arr[3],arr[4],arr[5])
result1=[]

for t in range(len(temp)): 
    tmp=[]
    tmp.append(np.quantile(temp[t],.25))
    tmp.append(np.quantile(temp[t],.50))
    tmp.append(np.quantile(temp[t],.75))
    result1.append(tmp)
    
print("18세 이하 1~3 분위:",result1[0])
print("19세 이상 ~ 22세 이하 (1~3 분위):",result1[1])
print("23세 이상 ~ 27세 이하 (1~3 분위):",result1[2])
print("28세 이상 ~ 33세 이하 (1~3 분위):",result1[3])
print("34세 이상 ~ 39세 이하 (1~3 분위):",result1[4])
print("40세 이상 (1~3 분위):",result1[5])

arr1 = np.zeros(len(jean1))
arr2 = np.zeros(len(jean2))
a1,a2 = arr1,arr2

for jeans in range(len(jean1)):
    if jean1[jeans]['rate'] !='':
        a1[jeans]=jean1[jeans]['rate']
    else:
        a1[jeans]=0
        
for jeans in range(len(jean2)):
    if jean2[jeans]['rate'] !='':
        a2[jeans]=jean2[jeans]['rate']
    else:
        a2[jeans]=0
        
arr= np.hstack((a1,a2))
result2=[np.quantile(arr,.25),np.quantile(arr,.50),np.quantile(arr,.75)]
print("별점 (1~3 분위):",result2)

a1,a2=arr1,arr2

for jeans in range(len(jean1)):
    if jean1[jeans]['tp'] !='':
        a1[jeans]=jean1[jeans]['tp']
    else:
        a1[jeans]=0
        
for jeans in range(len(jean2)):
    if jean2[jeans]['tp'] !='':
        a2[jeans]=jean2[jeans]['tp']
    else:
        a2[jeans]=0

arr= np.hstack((a1,a2))
result3=[np.quantile(arr,.25),np.quantile(arr,.50),np.quantile(arr,.75)]
print("총 구매수 (1~3 분위):",result3)


r=[result1[0],result1[1],result1[2],result1[3],result1[4],result1[5],result2,result3]

for p in range(6):
    for q in range(3):
        result1[p][q]=result1[p][q].item()

for q1 in range(3):
    result2[q1]=result2[q1].item()

for q2 in range(3):
    result3[q2]=result3[q2].item()

r=[result1[0],result1[1],result1[2],result1[3],result1[4],result1[5],result2,result3]

with open('../pickle/range/quantile.pickle', 'wb') as f1:
    pickle.dump(r,f1)

18세 이하 1~3 분위: [0.0, 14.0, 54.0]
19세 이상 ~ 22세 이하 (1~3 분위): [0.0, 49.0, 198.0]
23세 이상 ~ 27세 이하 (1~3 분위): [0.0, 61.0, 243.5]
28세 이상 ~ 33세 이하 (1~3 분위): [0.0, 29.0, 126.0]
34세 이상 ~ 39세 이하 (1~3 분위): [0.0, 10.0, 44.0]
40세 이상 (1~3 분위): [0.0, 10.0, 37.5]
별점 (1~3 분위): [0.0, 4.7, 4.8]
총 구매수 (1~3 분위): [0.0, 204.0, 725.0]

In [8]:
import numpy as np

a=[1,2,3,3,4,5,6,1]

b=np.arange(20)
c=np.arange(21)
d= np.concatenate((b,c),axis=0)

print(type(d))
k=list(d)
p=d.tolist()
print(d)
print(type(p))
print(type(k))
print(k)

<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19  0  1  2  3
  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
<class 'list'>
<class 'list'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]